### ISSUE TITLE
Error in using: docker pull nongbaoting/pisa:latest

### ISSUE THREAD

**Issue by Melonoyk** [nongbaoting/PISA#1]
I have met a problem when i using: docker pull nongbaoting/pisa:latest on Ubuntu 22.04.3 LTS.
My output is as follow:

'‘’
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=nongbaoting%2Fpisa&tag=latest": dial unix /var/run/docker.sock: connect: permission denied
'‘’

**Comment by nongbaoting** [comment]
This is because you don't have Docker permissions. Please ask your system administrator to add you to the Docker group using a command like this: `sudo usermod -aG docker username`. the __username__ is your user name in system
