### ISSUE TITLE
error when starting Web server

### ISSUE THREAD

**Issue by Melonoyk** [nongbaoting/PISA#2]
I have met a problem when I come to the step: Start Web server.  I have changed  the IP to my IP and get an error as output, the error is as follow:
'''
(base) jiangsw@dell-PowerEdge-R7525:~/other/PISA$ IP=172.18.20.151 
    docker run -it  \
        --add-host dockerhost:${IP}  \
        --gpus all \
        -v `pwd`:/apps \
        -p 9006:9006 \
        -p 9112:9112 \
        nongbaoting/pisa:latest /apps/startapp.sh
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
ERRO[0000] error waiting for container: 
'''

**Comment by nongbaoting** [comment]
You need to install [ nvidia-container-toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html), and don't forget to restart docker service
